version: 1
distro: fedora

meta:
  initramfs:
    files:
      - /usr/lib/modules/*/initramfs.img
      # - /usr/lib/modules/*
      # - /usr/lib/ostree-boot/*
  homebrew:
    files:
      - /usr/share/homebrew.tar.zst
  kernel:
    packages:
      - kernel*
      # Kmods
      - kmod*
      - nct*
      - ayn-platform*
      - ayaneo-platform*
      - bmi260*
      - ryzen-smu*
  mesa:
    packages:
      - mesa*
  firmware:
    packages:
      - linux-firmware*
    # files:
    #   # Bazzite dirty writes to /lib/firmware for the Steam Deck
    #   - /usr/lib/firmware/*
  kde:
    packages:
      - plasma*
      - kde*
      - kio*
      - kwayland*
      - kwin*
      - sddm*
  qt6:
    packages:
      - qt6*
  wine:
    packages:
      - wine*
  fcitx5:
    packages:
      - fcitx5*
    dedicated: False
  kf6:
    packages:
      - kf6*
  llvm:
    packages:
      - llvm*