FROM quay.io/coreos-assembler/fcos-buildroot:testing-devel as build

#
# Usage dependencies
#
# Done before building rpm-ostree to allow adding more patches.

# Install niceties
RUN dnf install -y skopeo buildah just git jq fuse-overlayfs \
    make bubblewrap fedpkg selinux-policy-targeted

#
# Build rpm-ostree
#

ARG RPM_OSTREE_TAG="v2024.6"
RUN mkdir -p /sources; \
    cd /sources; \
    git clone --branch ${RPM_OSTREE_TAG} --depth 1 \
    https://github.com/coreos/rpm-ostree rpm-ostree;

WORKDIR /sources/rpm-ostree

# Install dependencies
RUN git submodule update --init; \
    ./autogen.sh --prefix=/usr --libdir=/usr/lib64 --sysconfdir=/etc
RUN cargo fetch

# Apply patches
COPY 0001-skip-multiple-packages-check-to-avoid-32bit-packages.patch /tmp/patch.patch
COPY 0001-place-all-etc-files-in-the-last-layer.patch /tmp/patch2.patch
RUN patch -Np1 < "/tmp/patch.patch"; \
    patch -Np1 < "/tmp/patch2.patch"

# Make with patches (90s vs 5m)
RUN make
RUN make install

#
# Post-build niceties
#
WORKDIR /workspace